# Generated by Django 2.1.1 on 2019-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
