# Generated by Django 2.1.1 on 2019-01-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190128_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/tweets/mona.png', upload_to='static/tweets/'),
        ),
    ]
