# Generated by Django 2.1.1 on 2019-01-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190128_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/tweets/mona.png', upload_to='static/tweets/'),
        ),
    ]
