# Generated by Django 2.1.1 on 2019-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tsubuyaki_purchased_by'),
        ('accounts', '0012_auto_20190201_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purchased_tsubuyaki',
            field=models.ManyToManyField(blank=True, related_name='purchased', to='tweets.Tsubuyaki'),
        ),
    ]
