# Generated by Django 2.1.1 on 2019-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='key',
            new_name='token',
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
