# Generated by Django 2.1.4 on 2018-12-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsubuyaki',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='tsubuyaki',
            name='content3',
        ),
    ]
