# Generated by Django 2.1.4 on 2018-12-28 10:08

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20181228_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsubuyaki',
            name='content',
            field=models.CharField(max_length=130, validators=[tweets.validators.validate_content]),
        ),
    ]
