# Generated by Django 2.1.1 on 2019-01-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20181228_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tsubuyaki',
            options={'ordering': ['-timestamp']},
        ),
    ]
