# Generated by Django 2.1.1 on 2019-01-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190108_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsubuyaki',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Tsubuyaki'),
        ),
    ]
