# Generated by Django 2.1.1 on 2019-01-12 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0005_tsubuyaki_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsubuyaki',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
