# Generated by Django 2.1.1 on 2019-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tsubuyaki_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsubuyaki',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
