# Generated by Django 2.1.1 on 2019-01-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tsubuyaki_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsubuyaki',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/Tsubuyaki/'),
        ),
        migrations.AddField(
            model_name='tsubuyaki',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
