# Generated by Django 2.1.1 on 2019-01-30 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20190130_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsubuyaki',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
