# Generated by Django 2.1.1 on 2019-02-06 08:17

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tsubuyaki_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsubuyaki',
            name='title',
            field=models.CharField(default='No title', max_length=50, validators=[tweets.validators.validate_content]),
        ),
        migrations.AlterField(
            model_name='tsubuyaki',
            name='content',
            field=models.CharField(max_length=250, validators=[tweets.validators.validate_content]),
        ),
    ]
