# Generated by Django 2.1.1 on 2019-02-25 04:34

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_tsubuyaki_remickled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsubuyaki',
            name='content',
            field=models.CharField(max_length=500, validators=[tweets.validators.validate_content]),
        ),
    ]
